### ISSUE TITLE
Investigate a potential revision in error handling for the Peer

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#1025]
> Just a small comment update. Afterwards, I think this PR can be merged. However, in the grand scheme of things, I don't particularly like the idea of letting the writer and the reader handle the error blindly. In some cases, we might want to bubble the error up and let the server decide what to do depending on the error detected.

> There should be a way to do it without triggering a close channel panic. This can be achieved by wrapping the channel into a specialized SafeChannel struct that contains the channel, a sync.Once (or a mutex) to close the channel and a boolean to keep track of channel closure.

**Comment by autholykos** [comment]
With the recent migration of `kadcast` to Rusk process, the `Peer` in the dusk-blockchain is no longer handling network connections other than the GRPC interface exposed by Rusk.
