### ISSUE TITLE
Implement a `diskpool` for transaction storage

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#1059]
This will avoid potential OOM-reaper activations when running nodes with limited RAM.

**Comment by autholykos** [comment]
@julesdesmit is this still relevant? I remember that we implemented something like that when battling against the OOM issue

**Comment by autholykos** [comment]
To be assessed in the context of Testnet

**Comment by goshawk-3** [comment]
pendingPropagation queue should be also persisted on mempool closing.
