### ISSUE TITLE
Synchronizer is not capable of getting last block

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#106]
After downloading first block, synchronizer stops downloading any other blocks due to timeout-ed error on getLastBlock call to Chain component.

```
level=debug msg="block received" our height=0 process=synchronizer received block height=1
level=trace msg="procedure started" process="accept block"
level=trace msg="procedure ended" process="accept block"
level=debug msg="block received" our height=1 process=synchronizer received block height=2
level=trace msg="procedure started" process="accept block"
level=error msg="problem handling message block" error="timeout-ed request" process=peer
```
On further investigation, it turns out that the Chain component is stuck at locking mutex:

```
sync.runtime_SemacquireMutex at sema.go:71
sync.(*RWMutex).RLock at rwmutex.go:50
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).Listen at chain.go:94
runtime.goexit at asm_amd64.s:1333
 - Async stack trace
main.Setup at server.go:51
```

**Comment by ggoranov** [comment]
On questioning why this mutex is infinitely locked the call stack from below could give some hint:

```
math/big.nat.bytes at nat.go:1298
math/big.(*Int).Bytes at int.go:435
github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user.Provisioners.MemberAt at provisioners.go:51
github.com/dusk-network/dusk-blockchain/pkg/core/consensus/user.Provisioners.CreateVotingCommittee at sortition.go:90
github.com/dusk-network/dusk-blockchain/pkg/core/verifiers.checkBlockCertificateForStep at block.go:83
github.com/dusk-network/dusk-blockchain/pkg/core/verifiers.CheckBlockCertificate at block.go:74
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).AcceptBlock at chain.go:186
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).onAcceptBlock at chain.go:158
github.com/dusk-network/dusk-blockchain/pkg/core/chain.(*Chain).onAcceptBlock-fm at chain.go:77
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*callbackDispatcher).Publish at dispatcher.go:28
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*EventBus).publish at eventbus.go:237
github.com/dusk-network/dusk-blockchain/pkg/util/nativeutils/eventbus.(*EventBus).Publish at eventbus.go:219
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer/processing/chainsync.(*ChainSynchronizer).Synchronize at sync.go:84
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*messageRouter).route at router.go:67
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*messageRouter).Collect at router.go:35
github.com/dusk-network/dusk-blockchain/pkg/p2p/peer.(*Reader).ReadLoop at peer.go:216
runtime.goexit at asm_amd64.s:1333
 - Async stack trace
main.(*Server).OnConnection at server.go:163
```

**Comment by ggoranov** [comment]
It looks like the root cause is around the infinitely looping through https://github.com/dusk-network/dusk-blockchain/blob/master/pkg/core/consensus/user/sortition.go#L85

@julesdesmit  Do you have any clue what could be the reason?

**Comment by julesdesmit** [comment]
@ggoranov This is quite a rare bug, one which I believe to be caused by the sortition trying to extract more members than there are in the provisioner set.

It might be a regression from centralizing the provisioners on the chain.

**Comment by julesdesmit** [comment]
Note that #117 could fix this issue, however it would not work on the current network due to inconsistencies. When v2 launches, we should re-attempt syncing to see if it works properly.

**Comment by julesdesmit** [comment]
I think I've figured out the cause. This should be the culprit:
https://github.com/dusk-network/dusk-blockchain/blob/9a8ad2c76252dbc3093e4f108a56f656d57d0c49/pkg/core/verifiers/block.go#L83

The sortition would deadlock on the current master branch because it is trying to extract a voting committee with a size that exceeds the provisioner set. This caused other problems with the upgraded sortition code, as it would give an invalid signature error, when trying to verify a perfectly valid certificate.

#130 should fix this issue.
