### ISSUE TITLE
Balance returns 0 after any wallet transaction

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#107]
As per latest changes, the following rule was implemented:

```
Remove inputs from the db, to prevent accidental double-spend attempts when sending transactions quickly after one another.
```

As a side effect, `balance` command will always return 0 until next block is accepted.  Would we need to document this or handle it in another way? @julesdesmit 

```
> loadwallet password
Wallet created successfully!
Public Address: 2AabBNzuaTiF8wJ5KWSwLXY5wffH32LPEvJAZehw1g6WKqtTYgJxuvTo8FVjUD5UEoQRhBEtibfD1cMESFXXKAgCeXhGMh
> balance
25000000
> transfer 1234 2eMD4b8B1id1Xkt3ngttfYG2ESuP2UAarPDVF3URMtscZdmtvEjUdWU5GqmzqxfDanuNQcDvgeaE421HP5b912FMeRapXh
Txn Hash: 5ebdaa916d048187414cd9f318194a40b42cf59067031c514df731e05787a0a9
> balance
0
```

**Comment by julesdesmit** [comment]
Good catch. I wonder if there would be an easy way to have something like

```
> balance
0 (25000000 pending)
```

or something similar.

**Comment by ggoranov** [comment]
Indeed, currently a similar approach is being implemented where value tagged as `pending` would show the wallet outputs total balance from mempool (unconfirmed) txs

Another note worth mentioning is that the balance might be constantly printed as 0 as we've got sendBid/sendStake automated by StakeAutomation.

**Comment by julesdesmit** [comment]
> Another note worth mentioning is that the balance might be constantly printed as 0 as we've got sendBid/sendStake automated by StakeAutomation.

In a default configured case, the `StakeAutomaton` only sends a stake and bid once every 249900 blocks (if I remember the default offset being 100 correctly).

**Comment by ggoranov** [comment]
Makes sense. I'll double check.

Meanwhile, let me know if the scenario below works for us (it's already implemented)


#### Before sending transfer tx

> balance
Balance 1000.00000000, Unlocked Balance 1000.00000000
> transfer 0.00000200 2eMD4b8B1id1Xk...
Txn Hash: 6cde7ee0292897...

#### After sending transfer tx
`Unlocked Balance` shows the unspent wallet amount
`Balance `shows the sum of both wallet amount and pending to be received

> balance
Balance 999.99999700, Unlocked Balance 0.00000000

#### After tx is accepted
> balance
Balance 999.99999700, Unlocked Balance 999.99999700

**Comment by julesdesmit** [comment]
Yes this is fine! Feel free to open a PR for it.
