### ISSUE TITLE
Update required go version in Readme.md

### ISSUE THREAD

**Issue by ghost** [dusk-network/dusk-blockchain#1074]
As stated in the Readme.md, the minimum go version required is 1.14

By the way, trying to build the master branch with that version fails due to 
`pkg/core/mempool/mempool.go:159:10: ticker.Reset undefined (type *time.Ticker has no field or method Reset)`

`ticker.Reset` was added in 1.15

**Comment by herr-seppia** [comment]
Closed by #1190
