### ISSUE TITLE
Allow timer to expire before proceeding to the Reduction phase

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1160]

**Comment by goshawk-3** [comment]
As per spec comment from `specs/proposals/consensus-upgrade` and confirmed with @toghrulmaharramov ,  Selection step should wait for the `generationTimer` to expire before we proceed to `first step reduction`.

consensus-upgrade document:
> generationTimer = 4 seconds \\ The timer required to expire before proceeding to the Reduction phase

@toghrulmaharramov clarification:
>We need the timer to expire before proceeding to the Reduction timer because otherwise, the nodes can easily go out of sync, especially if the latency is enough to saturate the generation timer.

This should be also refined with @autholykos as we have `IncreaseTimeout` functionality which might be an issue if we always require the timer to expire.

**Comment by l0k18** [comment]
The type assertion inside the `if shouldProcess` block - if the type does not match, it will panic. I think the test clause in the if block following it should continue also if the type is wrong, with a 'comma, ok' syntax to catch it. Even, actually, collectNewBlock probably shouldn't be called unless the type assertion passes.

**Comment by l0k18** [comment]
I just noticed another thing too, not as important but you can leave out the explicit `continue` after the `collectNewBlock` if you flip the sense of the check on err (and conversely the `ok` from the type assertion).

I'm wondering about this spawning a goroutine to drain the timeout channel. Is there actually a scenario in which creating new channels will happen faster than the timeouts? I don't fully understand the to-and-fro of the protocol this is tied to, just that channels are a lot cheaper than goroutines.
