### ISSUE TITLE
Monitor hopping of consensus messages

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1184]
**Describe what you want implemented** 
Add timestamp of hopping directly inside the consensus messages 

**Describe "Why" this is needed**
This would help in gathering information about network state in case of problems (i.e. the consensus split)

**Describe alternatives you've considered**
If the payload would increase significantly and impact the analysis, an alternative would be to simply add a counter that gets incremented at every single hop

**Additional context**
This issue is related to the consensus network split #1156

**Comment by autholykos** [comment]
Rather than adding monitoring information directly in the payload or the header, a simpler and cleaner solution would be to log the message hash together with a timestamp. The monitoring of the hops and the various processing is then carried out directly in the Kibana dashboard

**Comment by herr-seppia** [comment]
No extra logging is required as far as we are able to reproduce the consensus split
