### ISSUE TITLE
Measure the bottlenecks in consensus message processing 

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1185]
**Describe what you want implemented** 
Log how much time the different processing takes for a consensus message

**Describe "Why" this is needed**
We need to understand where the bottlenecks of the node are in order to solve any inefficiency with the consensus

**Describe alternatives you've considered**
Increasing logging everywhere might add significant complexity to the analysis. Implementing a "tracing pill" message might lead to quicker results (i.e. monitoring a single message every so often).

**Additional context**
It might be that monitoring message transiting in the node is not going to lead to a meaningful insight.

**Comment by herr-seppia** [comment]
This issue is tackled by #1192
