### ISSUE TITLE
Solve context deadline exceeded error in Rusk Mock service

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1195]
**Describe the bug**
Sporadically, Rusk mock does not respond on time. As a result, dusk node reports `rpc error: code = DeadlineExceeded desc = context deadline exceeded` on block accept.  

**438** occurrences of DeadlineExceeded error on a cluster of 100 nodes for around **32737** rounds.

**To Reproduce**
It was noticed on a cluster of 100 nodes (72 provisioners). See also the attached screenshot log.

**Expected behaviour**
Considering Rusk mock service does only mocking, we accept that it should 

**Logs/Screenshot**
[deadline-errors.log](https://github.com/dusk-network/dusk-blockchain/files/7536224/deadline-errors.log)

**Comment by autholykos** [comment]
The rusk-mock is obsoleted by the migration to testnet
