### ISSUE TITLE
Create PR with proposal about protobuf schema

### ISSUE THREAD

**Issue by Fulviuus** [dusk-network/dusk-blockchain#1197]
We determined that there was a desync between the core and node team about the rusk protobuf schema and the related interfaces we had in place.
We will address the issues with a PR with a modification proposal of the current specs.

Current repo with the rusk schema (the one that should be used for future reference):
https://github.com/dusk-network/rusk/tree/master/schema

Original schema (deprecated)
https://github.com/dusk-network/rusk-schema

**Comment by herr-seppia** [comment]
PR has been created here dusk-network/rusk#373
