### ISSUE TITLE
Include Rusk executable in dusk-blockchain/bin

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/dusk-blockchain#1216]
**Describe what you want implemented** 
Test harness should run against rusk service instead of rusk mock (as per #1215)

**Describe "Why" this is needed**
The rusk executable should be included in a way that the Makefile will be able to run the tests in the correct way

**Describe alternatives you've considered**
There are different approaches to goal this issue:
1. Clone and build the rusk service In the Makefile:
    * Pro: Easy to setup
    * Cons: Time consuming operation due to keys creation
2. Download previously published rusk artifacts
    * Pro: Speed up CI execution time (rusk is already built)
    * Cons: Hard to setup the Makefile. We need to:
        1. Change rusk CI to publish 2 different version of rusk (ubuntu & macOS)
        2. Setup the Makefile to include GitHub API related to the tag-related artifacts download
3. Download rusk release
    * Pro:
        1.  Easy to setup
        2. Speed up CI execution time (rusk is already built)
    * Cons: It is fair to assume a lot of ReleaseCandidate being published
4. Manually include rusk executable
    * Pro:
        1.  Easy to setup
        2. Speed up CI execution time (rusk is already built)
    * Cons:
        1.  This is a mere workaround, hard to maintain and it should be deprecated when a stable rusk version will be released
        2. macOS developers should build linux distro too (and viceversa) to keep the codebase updated

**Additional context**
N/A

**Comment by Fulviuus** [comment]
As discussed, we are going to share the keys on an NFS share.
This has been setup and can be mounted on the deployed hosts.
Left to do:
- Configure the deployer to create all VPS in the same data center (so that they can mount the NFS share) [WIP]
- Move the keys to the NFS share [WIP]
- Change the makefile to build rusk on the machines

**Comment by autholykos** [comment]
Rather than NFS, `scp`-ing the prover key from the various regions is a better option that work around the complexity of NFS while also avoiding the penalty of Prover key recompilation

**Comment by autholykos** [comment]
This is missing adding the proper commands in the Makefile
