### ISSUE TITLE
Execute spreadsheet testplan, report and investigate issues

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1227]
**Describe what you want implemented** 
Testbed should be used to stress test kadcast network and a report of results should be generated and maintained.

**Describe "Why" this is needed**
The testplan defines a roadmap to follow in order to ensure both client and service are robust enough to drive a network. In case of an issue, further investigation should be performed to ease and support issue solving.

**Comment by autholykos** [comment]
Closing as rusk#394 has been long merged already
