### ISSUE TITLE
Network connectivity lost after rusk restart

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/dusk-blockchain#1256]
**Describe the bug**
If rusk is restarted, the node is isolated from the network

**To Reproduce**
Restart rusk

**Expected behaviour**
The node should retry to establish the connection with rusk

**Logs/Screenshot**
```
{"code":14,"error":"rpc error: code = Unavailable desc = transport is closing","level":"warning","msg":"listener_loop terminated","process":"kadcast","time":"2022-01-22T15:35:37Z"}
```

**Comment by autholykos** [comment]
Closing as this bug is actually a feature
