### ISSUE TITLE
Incorporate rusk.VerifyTransaction into mempool

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1273]
**Describe what you want implemented** 
On receiving a new transaction mempool does call  `proxy.VerifyTransaction` which has empty definition . `proxy.VerifyTransaction` should call rusk.VerifyTransaction.

NB: This is blocked until rusk provides rusk.VerifyTransaction and dusk-protobuf is updated.

**Comment by autholykos** [comment]
The return from `rusk.VerifyTransaction` should also carry the `Fee` https://github.com/dusk-network/rusk/issues/458
