### ISSUE TITLE
Resolve any incompatibility between Rusk transaction schema and Dusk transaction schema

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1274]
**Describe the bug**
Converting a Rusk transaction into Dusk Transaction and vice versa should be reviewed.

Functions to be reviewed:

- `transactions.MTransaction`
- `transactions.UTransaction`
- `transactions.MarshalTransactionPayload()`

In addition,

A list of pending (TODO) found in file `dusk-network/dusk-blockchain/pkg/core/data/ipc/transactions/transaction.go` should be taken into account (resolved) prior to Rusk integration.

**Comment by autholykos** [comment]
See https://github.com/dusk-network/rusk/pull/454#discussion_r793375157

**Comment by autholykos** [comment]
Solves #1273
