### ISSUE TITLE
Parse transaction payload structure to populate fields of the Block Explorer

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1281]
**Describe what you want implemented** 
A `decode` method that parses the notes and other useful information from the transaction's payload defined within Rusk

**Describe "Why" this is needed**
To populate fields in the block explorer that the user needs to see

**Describe alternatives you've considered**
Augmenting the result values of the gRPC calls `ExecuteStateTransition`, `Accept`, `Verify`

**Additional context**
See dusk-network/rusk#450

**Comment by herr-seppia** [comment]
Closed by #1282
