### ISSUE TITLE
Decode coinbase transaction paylaod

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1287]
**Describe the bug**
TransactionPayload.decode is panicking on any attempt to decode Coinbase payload.

```
"runtime error: makeslice: len out of range
```

**To Reproduce**
Calling TransactionPayload.decode for any Coinbase transaction returned by `ExecuteStateTransition` should be enough to reproduce it.

**Additional context**
In addition to `TestWireTransaction` unit test, we need to support `TestCoinbaseTransaction`, `TestStakeTransaction` and `TestTransferTransaction` unit tests.

**Comment by herr-seppia** [comment]
I’m aware of this.
Actual coinbase txs are just notes
Once they will be aggregate in a single tx with 2 output this should be solved

See also dusk-network/rusk#541
