### ISSUE TITLE
Assess the real usefulness of the MAGIC header parameter and eventually remove it

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1294]
**Describe what you want implemented** 
Removal of the MAGIC parameter from the header of the messages

**Describe "Why" this is needed**
The MAGIC has so far been the source of issues and wild goose chases when debugging the protocol. Removing it would probably have no real consequence in the economy of the network

**Describe alternatives you've considered**
Live with it

**Comment by herr-seppia** [comment]
removed in #1337
