### ISSUE TITLE
Protocol versioning behaviour

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1319]
**The protocol versioning needs to be properly specc'ed**

- If the nodes receive a message with a version that cannot be processed (since it is newer), they should ignore the message
- when we do the handshake with the bootstrapper, the version of the protocol (and the node, and rusk) should be validated. The bootstrapper will probe the version communicated by the nodes and returns a string with the link to where a newer version shall be downloaded
- the ping/pong could be used to communicate/inquiry the protocol version
- in the header of the messages we should add the protocol version
- consensus version shall remain backward compatible (and therefore consensus version should not influence protocol version)
- protocol changes need to be assessed on a case-by-case basis

## Version binary format

The version is represented as a 64-bit number (8 bytes) loosely following[^1] [semantic versioning]( https://semver.org/) with the format below:

| Field | Offset | Type |Description |
| - |  - | - | - |
| RESERVED | 0 | n/a | For future use |
| MAJOR | 2 | `u16` LE[^2] | version with incompatible API changes |
| MINOR | 4 | `u16` LE| version with added functionality in a backwards compatible manner |
| PATCH  | 6 | `u16` LE | version with backwards compatible bug fixes |

### Testnet

Testnet is always considered with `MAJOR` field set to `0`[^3], therefore the semantic of the field is shifted, merging all backwards compatible changes together[^4]:

| Field | Offset | Type |Description |
| - |  - | - | - |
| RESERVED | 0 | n/a | For future use |
| MAJOR | 2 | `u16` LE | Initial development, value blocked to `0x00` |
| MINOR | 4 | `u16` LE | version with incompatible API changes |
| PATCH  | 6 | `u16` LE |version with any backwards compatible changes |

[^1]: We don't have additional labels for pre-release and build metadata, as the semantic versioning allows.
[^2]: Little Endian
[^3]: Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable. https://semver.org/#spec-item-4
[^4]: This is consistent with the semver we have in rust development in Dusk

**Comment by herr-seppia** [comment]
> * If the nodes receive a message with a version that cannot be processed (since it is newer), they should ignore the message

if a node ignore completely the message it will break the propagation. Still cannot figure out if this can lead to problems....

> * when we do the handshake with the bootstrapper, the version of the protocol (and the node, and rusk) should be validated. The bootstrapper will probe the version communicated by the nodes and returns a string with the link to where a newer version shall be downloaded
the ping/pong could be used to communicate/inquiry the protocol version

As discussed with @ZER0, we should avoid to mix network layer version with application layer ones
Said that, 2nd and 3rd points should be stroke.

At startup Golang part is the one responsible to check the current rusk compatibility, and we can have 3 different scenarios
1) Rusk greater than go --> Halt and ask for go upgrade
2) Go greater than rusk --> Halt and ask for rusk upgrade
3) No major changes --> Compatibility guarantee

> * in the header of the messages we should add the protocol version

We should reuse the magic bytes
