### ISSUE TITLE
Decrease bandwidth consumption by repropagating valid score messages only at predetermined time-slots

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#135]
The `Selector` re-propagates `Score` events every time it verifies a new Score higher than the current one. This leads to quite some waste since the Provisioners care only for the highest score. In consideration of the fact that the `Selector` elects a Score after a timeout (currently every 5 seconds), a strategy in which the currently known best score gets forwarded only at regular time slots can reduce the load on the network while simultaneously allow for concurrent verification of scores and dropping the nasty lock in `Selector.CollectScoreEvent`.

To avoid introducing excessive latency, we would likely need to make the intervals frequent enough.

**Comment by julesdesmit** [comment]
Obsolete due to changes to selection phase.
