### ISSUE TITLE
Investigate use of sync.ErrGroup for error propagation within goroutines

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#136]
https://godoc.org/golang.org/x/sync/errgroup

**Comment by julesdesmit** [comment]
This seems mostly useful for parallel tasks, so it may be a good addition to #49

**Comment by autholykos** [comment]
This issue is too generic. In case we introduce some parallelization, we should consider ErrGroup, but for now this is not needed
