### ISSUE TITLE
Register a vote locally before sending my own reduction 

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1360]
**Describe the bug**
Currently, any committee member relies on other provisioners to propagate their own votes back in order to be registered locally. As a side effect of this, `CollectReduction` always need to initiate a kadcast broadcast with `config.KadcastInitHeader`. 

**To Reproduce**
TBD.
 
**Expected behaviour**
As suggested by @herr-seppia , `CollectReduction` should re-propagate kadcast reduction messages instead of initiating a new broadcast (kad_h=128). This to happen, a committee member must register its own first.

**Comment by herr-seppia** [comment]
**To Reproduce**
Launch a single node cluster with a single provisioner genesis block.
Consensus won't start

**Comment by goshawk-3** [comment]
> **To Reproduce** Launch a single node cluster with a single provisioner genesis block. Consensus won't start

The ultimate goal of this issue is to optimize `message.Reduction` propagation by reducing the number of messages per a single propagation. 
For having single-node network reaching consensus, we'll need to file another issue to register locally `topics.Agreement` too.
