### ISSUE TITLE
Phoenix notes

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/dusk-blockchain#142]
When a block generator executes a smart contract, it will produce a transparent and a obfuscated note for the gas fee reward.

The transparent note structure is as follows:
* `id`, identifier enum - Transparent
* `v`, Reward value
* `pk`, Public key (stealth addr)
* `R`, Diffie-Hellman randomness
* `pos`, Position in the tree

The obfuscated note structure is as follows:
* `id`, Identifier enum - Obfuscated
* `c`, Zero-knowledge commitment to the value
* `pk`, Public key (stealth addr)
* `R`, Diffie-Hellman randomness
* `pos`, Position in the tree
* `venc`, Value encrypted to `pk`
* `benc`, Blinder encrypted to `pk`

**Comment by julesdesmit** [comment]
Closing, since this is implemented in rust in a different repo
