### ISSUE TITLE
Merkle Tree database for the notes

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/dusk-blockchain#143]
The merkle tree will use the following parameters:

Arity `4`
Width `2^34`

The hash function will be poseidon
https://github.com/dusk-network/dusk-go-poseidon

It will receive the transparent and obfuscated notes, perform the sponge function, and append to the tree.

The input for this tree is defined by #142

**Comment by julesdesmit** [comment]
Closing, as this is implemented in rust in another repo.
