### ISSUE TITLE
Verify block certificate prior to broadcast 

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#1446]
**Describe the bug**
On receiving a block from Kadcast network, we used to fully verify it before re-propagating it to the next bucket. Now to speed up block broadcast to all provisioners, we re-propagate it without any checks. 

Checking a certificate and block header should be a precondition for a block propagation.

**Comment by herr-seppia** [comment]
In this case, txs root should be reintroduced

**Comment by goshawk-3** [comment]
> In this case, txs root should be reintroduced

This should be addressed with a separate issue that may also take into account the backward compatibility.
