### ISSUE TITLE
Go Get no longer supported

### ISSUE THREAD

**Issue by TurtleSnail** [dusk-network/dusk-blockchain#1536]
**Describe the bug**
Since version 1.17.1 of Go, it is no longer possible to use the `go get` command.

**To Reproduce**
Make sure you have a Golang version above 1.71.1 installed:
```shell
go version
```

Run `go get` as specified in the `README`:
```shell
go get github.com/dusk-network/dusk-blockchain
```

The following output will appear:
```
dusk@m19221:~$ go version
go version go1.21.0 linux/amd64
dusk@m19221:~$ go get github.com/dusk-network/dusk-blockchain
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**Expected behaviour**
The codebase and its dependencies should be downloaded.

**Comment by HDauven** [comment]
@TurtleSnail `go get` as written in our README no longer behaves as expected after Golang 1.17. This will be updated, thank you for your report.

Meanwhile, if you would like to play with our node software, I would strongly advice you to look at our [Rusk](https://github.com/dusk-network/rusk/tree/master) repository instead. `dusk-blockchain` will be deprecated in favor of `rusk` in the future.

There's multiple ways to run and test our Rusk node. For more details see our [setting up a node](https://wiki.dusk.network/en/setting-up-node) wiki page.
