### ISSUE TITLE
Import crypto from dusk-network/dusk-crypto rather than subtreeing it directly in the project

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#16]
Dusk-blockchain uses the crypto package embedded directly in the codebase. It should instead import [dusk-network/dusk-crypto](https://github.com/dusk-network/dusk-crypto) and treat it as an external package

**Comment by u5surf** [comment]
I tried to replace submodules, but https://github.com/dusk-network/dusk-crypto is wrong import path which should be `github.com/dusk-network/dusk-crypto`. 
e.g. 
https://github.com/dusk-network/dusk-crypto/blob/master/crypto.go#L9
