### ISSUE TITLE
Sortedset perf improvement on inserting

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#171]
`util/nativeutils/sortedset` currently uses quicksort (sort.Sort()) on each Insert call.  As the elements are kept sorted a  BinarySearch&Shift approach could be an option to experiment with:

Pseudo:

```go
   func (v *Set) Insert(b []byte) {
       ...
        ind := sort.Search(len(data), func(i int) bool {
		return data[i] > iRepr
	})

	data = append(data, &big.Int{})
	copy(data[index+1:], data[index:])
	data[ind] = iRepr
```

Some observations wrt topic:
https://github.com/dusk-network/dusk-blockchain/issues/169#issuecomment-561630839

**Comment by autholykos** [comment]
Confirmed. Benchmark show a substantial improvement of 87% by using the binary search + shift approach
