### ISSUE TITLE
Candidate blocks should be kept in an in-memory storage, instead of the DB

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#173]
The DB is currently used as a temporary data dump for potential candidates. It would be more readable and more effective to use an in-memory store for managing these candidate blocks.

**Comment by autholykos** [comment]
What are the operations to be performed on the in-memory storage?

**Comment by julesdesmit** [comment]
@autholykos Merely storing, fetching and deleting `Candidate` messages. Storage and fetching done by using the hash of the included block as a key for a map. Deleting would be done on a per-round basis, so the store would iterate over and delete any `Candidate` messages which are on or below the given round.
