### ISSUE TITLE
Implement peerSet as HashSet data structure for LRU policy.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-blockchain#179]
Discussing with @autholykos in #141, he stated that implement peerSet will be a better solution so we will implement it for the LRU policy.

So we can get rid of one of the maps used in `Bucket` and reduce the code while improving its readability.

**Comment by CPerezz** [comment]
As discussed here:
https://github.com/dusk-network/dusk-blockchain/pull/141#discussion_r355353421

We can leave this for the future and focus on finish a functional implementation for Kadcast.

**Comment by autholykos** [comment]
This issue is obsolete. Kadcast implementation has been overhauled within the `Kadcast` Epics
