### ISSUE TITLE
Prevent random CI failures

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#189]
Some of the tests in the `maintainer` and `transactor` package have a tendency of randomly failing. It would be nice to find the source of these issues and fix them so that the CI will no longer randomly fail because of code unrelated to whatever change was committed.

**Comment by autholykos** [comment]
captured one of these intermittent failures on `TestLockedInput`. More info below:

![Screenshot from 2020-01-11 12-12-25](https://user-images.githubusercontent.com/7613527/72203490-845cad80-346c-11ea-96bf-be6298b65709.png)

**Comment by autholykos** [comment]
And another one on `TestMaintainStakesAndBids`:

![Screenshot from 2020-01-11 12-20-13](https://user-images.githubusercontent.com/7613527/72203558-5deb4200-346d-11ea-8403-4e6b24dea28b.png)
