### ISSUE TITLE
Mempool should clear invalid transactions after each new block

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#224]
When a block is accepted, certain transactions in the mempool can become invalid. This can cause a block generator to generate a block with an invalid transaction, missing it's chance to win the lottery.

**Comment by ggoranov** [comment]
Currently, mempool (verified set) removes only transactions that have been accepted in latest block.

How do we define the transition from a valid_tx state to invalid_tx state? In what cases a valid mempool tx becomes invalid?

**Comment by julesdesmit** [comment]
After some further investigation, it does not seem to be the cause. I am still trying to pinpoint where it is coming from. This issue can be closed for now, as doing extra checks did not seem to fix the issue.
