### ISSUE TITLE
Synchronizer is constantly switching to 'syncing' mode

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#225]
Even when the difference between local tip and network tip is 1, the node is constantly switching to "Syncing mode", restarting the syncing procedure. 

- It should be checked if it's intentional due to latest consensus changes. 
- Confirm if is the root cause for https://github.com/dusk-network/dusk-explorer/issues/29

```
time="2020-01-02T11:05:33+02:00" level=debug msg="Start syncing from 142.93.238.198:7000" process=synchronizer
time="2020-01-02T11:05:33+02:00" level=debug msg="Local tip: height 37720 [uERs+0eecSHcNbg3xPrIxtBGL+V6CCC7hIeyyVuzZII=]" process=synchronizer
time="2020-01-02T11:05:45+02:00" level=debug msg="Start syncing from 134.209.91.160:7000" process=synchronizer
time="2020-01-02T11:05:45+02:00" level=debug msg="Local tip: height 37722 [JRNxFO06FZS3tNJABy6KZWHfnzBdjliKyk4x9ZoC4AQ=]" process=synchronizer
time="2020-01-02T11:05:57+02:00" level=debug msg="Start syncing from 142.93.238.198:7000" process=synchronizer
time="2020-01-02T11:05:57+02:00" level=debug msg="Local tip: height 37724 [Eb0JEzs7aMEEZXpaixbjn2P4C9JE05Y9h94DVXXGfkg=]" process=synchronizer
time="2020-01-02T11:06:10+02:00" level=debug msg="Start syncing from 134.209.91.33:7000" process=synchronizer
time="2020-01-02T11:06:10+02:00" level=debug msg="Local tip: height 37726 [kuNb7QC6RuZJDa7vS8V0II938CZY7v6NkltgUyqhN/A=]" process=synchronizer
time="2020-01-02T11:06:22+02:00" level=debug msg="Start syncing from 142.93.238.198:7000" process=synchronizer
time="2020-01-02T11:06:22+02:00" level=debug msg="Local tip: height 37728 [uzHG1dHBVn0CQ5gS0TLMGtyOUEp5sCNTfnGcdS68F7w=]" process=synchronizer
time="2020-01-02T11:06:34+02:00" level=debug msg="Start syncing from 134.209.91.177:7000" process=synchronizer
time="2020-01-02T11:06:34+02:00" level=debug msg="Local tip: height 37730 [BOjZk9p+G6wog3T3PlOg+1LEAmchBcqF1fuBF1d04Zs=]" process=synchronizer
time="2020-01-02T11:06:47+02:00" level=debug msg="Start syncing from 134.209.91.33:7000" process=synchronizer
time="2020-01-02T11:06:47+02:00" level=debug msg="Local tip: height 37732 [IHunvtcS6T0wLrzYFxz0voMao1lLlxhX9EjNsKBaGy0=]" process=synchronizer
time="2020-01-02T11:07:00+02:00" level=debug msg="Start syncing from 134.209.91.33:7000" process=synchronizer
time="2020-01-02T11:07:00+02:00" level=debug msg="Local tip: height 37734 [VdJBvivIDAAm37GRzCJiEkLulcAug/BmrGcCEbkodGM=]" process=synchronizer
```

**Comment by julesdesmit** [comment]
Yes, this is intentional. The `dusk-blockchain` node is expected to run consensus, and so it does not immediately accept a block that is only 1 step away from it's current tip. This is because the node is likely to finalize on this block himself in a short moment, and when accepting a block from a peer, it triggers the shutdown of consensus, and it enters 'dozer mode' as outlined by @toghrulmaharramov. Allowing for the node to finalize the block by itself increases consensus stability.

If it causes issues for the explorer, one fix would be to build an edge-case into the block acceptance procedure for nodes that are in wallet-only mode (though I think we should get rid of that configuration option once we have a light node ready).

**Comment by julesdesmit** [comment]
With that said, it is also very likely that it is the cause of the issue you linked. Since the node will only accept blocks if it is 2 behind, it makes sense for the blocks to come in pairs.

**Comment by ggoranov** [comment]
It's good you record that. For now I'll close both issues and keep the block explorer as it is in order to reflect the real mechanism of blocks acceptance.
