### ISSUE TITLE
Move Chain messages to protobuffer

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#233]
In preparation for the modularization of the `EventBus`, IPC messages need a better serialization protocol than the home-grown wire encoding. Hence, we are migrating them to protobuffer. `Chain` is a good place to start as it is external to the Consensus and would likely talk with different rust processes (i.e. Phoenix, etc) and go (i.e. consensus, etc)

**Comment by julesdesmit** [comment]
This can be closed, as the short-term architecture plans have changed since this issue was opened.
