### ISSUE TITLE
Help nodes falling-behind to catch up

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#24]
Due to some unexplained issue, some nodes during deployment can fall behind and never sync up with the rest of their peers. My hunch is that it is due to some nodes not accepting every block after finishing consensus, which ends up in a gap in their blockchain, and then when someone asks to sync with them, they only supply about half the blocks and leave the requesting node hanging. Need to do more testing to confirm this.

To quote @toghrulmaharramov 
> we have to work on formalizing a bootstrapping model for the nodes that have fallen behind for less than `n` blocks. Unfortunately, due to the complexity of `Reduction phase`, which muddles up the bootstrapping process, the catch-up process has to be made more complex than on rival protocols. I have a few ideas on how the problem could be elegantly curtailed

**Comment by julesdesmit** [comment]
Worth mentioning that the first paragraph denotes an issue which was solved earlier, which caused some nodes to not receive an agreed-upon block, which then caused them to get stuck in the subsequent rounds.

What Tog is referring to is more like a consensus-related enhancement rather than a fix for a bug.

**Comment by julesdesmit** [comment]
Upon further discussion with Tog, this catch-up protocol requires implementation of a wire message to request agreement events for a certain round. Nodes should thus cache their received agreement events for a couple rounds, in case any lagging node needs them.

Note that this is only necessary if the lagging node is only behind one round. If it is more than one round behind, it can simply sync it's blockchain to the tip, minus one block, and then request agreement events for the last block to catch up.

Quoting @toghrulmaharramov:
>If the node falls back by more than a block, it is essentially a bootstrap process which requires the nodes to download the blocks preceeding the highest one with only the certificates and then the highest one with the certificate and the agreement messages
