### ISSUE TITLE
Public service for Tx query

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/dusk-blockchain#247]
Create a service with a synced node behind it that provide query methods for:

1) A phoenix note for a given position
1) The existence of a given nullifier
1) A list of notes for a given view key

The last two methods must be used with caution, because the nullifier will be exposed, as the view key. A malicious server can use this data to reverse engineer the wallet balance. There should be some designed anonymity.

**Comment by julesdesmit** [comment]
This is actually an awesome idea. If we can guarantee proper anonymity this could make light node implementations really really simple.
