### ISSUE TITLE
Make topic encoding independent of the declaration order

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#280]
The `topics.Topic` is an enum implicitly ordered due to the `iota` syntax. At the moment, the lookup of a topic, given its byte representation, is a simple and unchecked array index access. This means that, upon addition of a topic, one must make sure manually that the number expressed through its byte representation is kept consistent with the index of that topic within the enums. This is error prone and could lead to significant timesinks in case of mistakes. 

A way to enforce and check this consistency at startup would be to introduce an ordering within the `topicBuf` (the _struct_ holding the various topic's byte and string representation) and perform the consistency checks within an `init()` function

**Comment by autholykos** [comment]
Unfortunately, golang's `reflection` package does not support dynamic lookup of package declared constants. Therefore the only consistency check we can support is that the index of the `topicBuf` reflects the index within the enum (since it is an enum of consecutive `uint8`).
