### ISSUE TITLE
Subtract 1 DUSK when a node is extracted with deterministic sortition

### ISSUE THREAD

**Issue by toghrulmaharramov** [dusk-network/dusk-blockchain#29]
The current version of deterministic sortition does not decrease the available stake of a node one or more DUSK of which has been already extracted for the committee. The deterministic sortition procedure has to be upgraded to subtract 1 DUSK from the stake available during an instance of sortition procedure when a DUSK under the control of the node is extracted for the committee.

**Comment by julesdesmit** [comment]
Note that this subtraction of DUSK is only for the given step. It should serve only as a way to decrease chance of multiple extraction for one node.
