### ISSUE TITLE
Update P2P message documentation

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#293]
**Frame header**

As per impl of `processing.WriteFrame`, P2P frame header consumes 8 octets (64bits) whereas the maximum value it is allowed to store (MaxFrameSize: 250000) needs not more than 3 octets.

Option could be to document explicitly that P2P frame header has extra 5 bytes the semantics of which is undefined a.k.a reserved. In future, these bytes could be used for frame flags, identifiers etc.

**Length-prefixing frame**

Currently, README mentions `COBS encoded frames of data`. Instead it should say:
`All frames begin with a fixed 8-octet header followed by a variable-length payload not longer than 250000 bytes`

**Comment by ggoranov** [comment]
WRT frame header size,
Another option could be to reconsider frame header length and eventually reduce it to 4 byte?

@julesdesmit @autholykos

**Comment by julesdesmit** [comment]
Fixed via #922
