### ISSUE TITLE
Formulate a set-up for a light node to be able to use Phoenix with as little overhead as possible

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#302]
The goal is having at the bare minimum, a cache of notes which belong to the wallet user, foregoing the need to store the entire Phoenix database, and (hopefully) the need for the VM as well.

**Comment by autholykos** [comment]
This is obsoleted by the opportunity to have a web client (thanks to the Schnorr signature scheme). Closing
