### ISSUE TITLE
Make eventbus/rpcbus topics constant

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#320]
As we use `iota`, inserting a new topic would increment values of all topics after the insertion. That would alter RPC or P2P protocol (depending of the insertion).

E.g Inserting new RPCBus topic  `StartProfile`  after `SendMempoolTx` would increment both  `Cross-process RPCBus topics` and `Cross-network RPCBus topics`.

That could be avoided by simply appending topics to the iota list (no insertions) but a more robust solution would be to keep topics id constant.

```go
// A list of all valid topics
const (
	// Standard topics
	Version Topic = iota
	VerAck
	Ping
	Pong

	// Data exchange topics
	Addr
	GetAddr
	GetData

	// Gossiped topics
	Candidate
	Score
	Reduction
	Agreement

	// Peer topics
	Gossip

	// Error topics
	NotFound
	Unknown
	Reject

	//Internal
	Initialization
	RoundUpdate
	BestScore
	Quit

	// RPCBus topics
	GetLastBlock
	GetMempoolTxs
	GetMempoolTxsBySize
	VerifyCandidateBlock
	GetLastCertificate
	SendMempoolTx
            StartProfile

	// Cross-process RPCBus topics
	// Wallet
	GetMempoolView
	CreateWallet
	CreateFromSeed
	LoadWallet
	SendBidTx

	// Cross-network RPCBus topics
	GetRoundResults
	GetCandidate
)
```

**Comment by ggoranov** [comment]
@autholykos @julesdesmit Raising this here to discuss later.

**Comment by devtomnl** [comment]
this seems to be obsolete as @julesdesmit indicated today.
