### ISSUE TITLE
Assess if CHUNK message would be desirable to exchange blockchain data over UDP between nodes rather than falling back to TCP

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#354]
Apart from PING, PONG, FIND_NODES, NODES, shouldn't we support CHUNK message to exchange blockchain data between nodes?

If so, with regard to UDP use as a transport, do we have any idea how to cope the IP fragmentation in case of datagram size exceeding the default MTU size?

@CPerezz @autholykos

_Originally posted by @ggoranov in https://github.com/dusk-network/dusk-blockchain/pull/194#issuecomment-596356044_

**Comment by autholykos** [comment]
Initially the decision to revert to TCP for block communication was done in order to avoid the complexity of packet ordering and loss. However, TCP also introduces some quirks (see #353)

**Comment by ggoranov** [comment]
This has been addressed with implementing #562
