### ISSUE TITLE
Evaluate persistent TCP connection and optimal number of connected peers

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#355]
Closing TCP connection after each Write would trigger TCP handshake/TCP teardown procedure on each sendTCPStream. Would it make sense to reuse the TCP connection or this is not applicable?

_Originally posted by @ggoranov in https://github.com/dusk-network/dusk-blockchain/pull/194_

**Comment by ggoranov** [comment]
This has been addressed by implementing RaptorCode over UDP. #562
