### ISSUE TITLE
Chain committee is one round behind consensus committee during launch

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#36]
Since a `committee.Store` is initialized on the chain tip height, and a consensus round is always one ahead of the tip, it can cause a discrepancy between the chain and the consensus committees.

For example, if the chain tip is at block 2000, then the round is 2001. Upon startup, consensus components run `RemoveExpiredProvisioners` with round 2001, so their committee is then one step ahead of the chain, who only calls this function when blocks are accepted.

As a result, this can cause the node to get stuck, since a forged block will have an invalid certificate according to the chain, even though it is correct from a consensus point of view.

**Comment by ggoranov** [comment]
@julesdesmit Are you able to reproduce the issue locally?  If so, could you write here the steps to follow in order to observe it.

**Comment by julesdesmit** [comment]
@ggoranov Sure, though it would require some meticulous setup. I will outline the steps

- Have a provisioner in the committee, with a stake that ends at height N
- Have the blockchain tip be at height N also
- Start up the node, and then initialize consensus at round N+1. The committees between the agreement and reduction component should differ from the one in the chain. A good way to find out would be to forge a block for height N+1, and then attempt to accept it. The chain will give a BLS signature error, related to the certificate.
