### ISSUE TITLE
Substitute legacy wallet with Rusk RPCs

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#363]
The following changes should happen in the repository in order to fully support Phoenix as a transaction model accessed through rusk process:

## Database
- Blocks should now store phoenix transactions (generated protobuf structures)
- Locktimes and related functions no longer need to be recorded, as locking up of stakes and bids will happen through a contract
- KeyImages and related functions will no longer need to be recorded, as the mempool (using a phoenix RPC call) and the state transition function should guard against double spends
- FetchDecoys will no longer be needed

## Chain
- `restoreConsensusData` can be removed, as consensus data can be fetched from global storage.
- No longer needs to hold the bidlist and provisioners. Instead, when updating the round, it should get these from the global storage.
- `addConsensusNodes` and all related functionality can be removed
- `AcceptBlock` should make a call to ExecuteStateTransition (RPCBus topic already exists), right after `verifiers.CheckBlock`
- `removeXXX` functions for provisioners and block generators can be removed

## Verifiers
- Transaction file can be removed entirely, or can be whittled down to one single function which calls a phoenix RPC call to verify a transaction. NOTE that this call should not verify the proof - it should simply do some correctness checks on the tx values. The proof is verified later, in the smart contract execution.
- Tx related functions in block file can be removed. This includes `CheckMultiCoinbases` and `CheckTx` calls.

## Mempool
- Depending on transaction verification overhaul, either call VerifyTransaction directly over the RPCBus, or use the method in the `verifiers/transaction.go` file.
- `CheckTxDoubleSpent` can be removed, as VerifyTransaction should check for double spends by scanning for the nullifier in the nullifier set
- Should get a method which takes a slice of phoenix transactions, that have failed execution during block generation. This way, obsolete transactions can be removed each round.

## Transactor
- All dusk-wallet related logic needs to be replaced for phoenix RPC calls where appropriate, as all of the logic will reside in a rust process.

This list may be incomplete for the time being, but it should cover most of the affected areas.

**Comment by autholykos** [comment]
In order to merge this issue, the Rusk server needs to expose the right RPCs

**Comment by julesdesmit** [comment]
Fixed via #450
