### ISSUE TITLE
Refactor data package and migrate block-related data structures to the most appropriate package within pkg/consensus

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#365]
Since dusk-wallet is deprecated and transaction creation/validation is going to be moved to rusk, data structures used within the Mempool, the Chain and elsewhere within dusk-blockchain repo, the data structure definitions need to be migrated where they are actually used.

The BLS keys should also be migrated away from dusk-wallet as they are used by the node (Provisioner part) to sign the consensus messages.

As an outcome of this refactoring, the `core/data` package should be removed or contain only a fraction of the struct definition and functionalities.

Depends on #409 #410 #411 #363

**Comment by julesdesmit** [comment]
Fixed via #450
