### ISSUE TITLE
Chain should no longer take care of managing the provisioners and the bidlist

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#433]
It should instead retrieve them from Rusk, as they are managed by contracts.

This is a smaller issue, flowing forth from #363

**Comment by autholykos** [comment]
Within the `AcceptBlock` method within the `chain` component, the call to rusk's `ExecuteStateTransitionFunction` method gets performed. Immediately after the valid execution of the call, the chain scans the transactions for bids and stakes. If there are new bids and stake transactions, it modifies the Provisioner and bidder lists.

**Comment by julesdesmit** [comment]
Fixed via #472
