### ISSUE TITLE
Transactor: CreateWallet

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#436]
* Make a call to Rusk, method GenerateSecretKey. It takes some bytes as a seed, but this can be randomly generated in the function itself.
* Once the secret key is received, the Transactor should set it on its struct.
* The secret key needs to be stored on disk, in an encrypted file. In the past, we had an AES-encrypted wallet.dat file which needed a password to decrypt.
* Make another call to rusk, method Keys. This returns the view key and public key.
* Return the public key.

Related to #411

**Comment by julesdesmit** [comment]
Fixed via #450
