### ISSUE TITLE
Transactor: Bid

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#442]
* Make an internal call to the block generator, to retrieve the blind bid M value. (Scalar)
* Make a call to rusk, method NewTransaction. (NOTE: NewTransaction does not yet currently support adding any peripheral data to transactions. You can leave a TODO there for now.)
* Send the received transaction to the node's mempool (this can go over the event bus, or the rpc bus).
* Return the tx hash.

Related to #411

**Comment by julesdesmit** [comment]
Fixed via #450
