### ISSUE TITLE
CheckBlock does too many things

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#479]
Previously, `loader.CheckBlock` in the `Chain` component was performing consistency checks on the Block as well as verifying all its transactions. Since the latter operation is now delegated to the `Executor`, this operates an unnecessary double verifications of all transactions within the `AcceptBlock` method. A better solution would be to limit `CheckBlock` to the consistency check and use the `Executor` explicitly where needed so to avoid unnecessary call duplication

**Comment by julesdesmit** [comment]
Fixed via #472
