### ISSUE TITLE
Confusing description of locktime in README.md

### ISSUE THREAD

**Issue by Rigorously** [dusk-network/dusk-blockchain#5]
In README.md `locktime` is confusingly described as an amount of blocks that must exceed the block height. That means locktime must be at least as long as the age of the chain, which seems excessive and impractical.

> ` [locktime]` stands for the amount of blocks for which the bid is locked (`block_height < locktime < 250000`)

Additionally the maximum `locktime` is 250,000 blocks, which at the current average blocktime of 7 seconds is 20 days. After 20 days the block height will pass 250000, at which point there is no value for `locktime` which would satisfy `block_height < locktime < 250000`.

**Comment by julesdesmit** [comment]
Good catch! I will update it.
