### ISSUE TITLE
Reuse underlying transaction for amount-related fields in genesis contracts

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#501]
We should reuse the `Value` or `EncryptedValue` fields whenever possible for the various amounts of the genesis transactions. This translates into the following:
- `TotalReward` amount for `Distribute` contract call
- `Amount` or the `Stake` contract call
- `EncryptedValue`/`EncryptedBlinder` for the `Bid` contract call

**Comment by julesdesmit** [comment]
Fixed by #504
