### ISSUE TITLE
A custom type for hash with a predefined String() method

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#53]
Yes. Maybe it would make sense to use a custom type for `hash` with a predefined `String()` method that Hex encodes the `[]byte`?

_Originally posted by @autholykos in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTkyMTk1OTc4OnYy/pull_request_review_threads/discussion_

**Comment by autholykos** [comment]
We now have the `util.StringifyBytes` that allows for more readable string representation of `[]byte`
