### ISSUE TITLE
Consensus is not initialized when running the network from genesis block

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#54]
When starting a local network from scratch (for testing purposes) it seems no nodes are running the consensus.

According to the current implementation, `msg.InitializationTopic` is published in case of topics.AcceptedBlock event only which is totally fine for updating the consensus module with the chain tip. 

However, in case of starting the network from genesis block, wouldn't the network get stuck as no node is able to generate block at height 1?

@julesdesmit  The below patch workarounds this but need your expertise here, if I'm missing something?
```
+++ b/pkg/core/consensus/initiator.go
@@ -35,6 +35,13 @@ func GetStartingRound(eventBroker wire.EventBroker, db database.DB, keys user.Ke
        // Start listening for accepted blocks, regardless of if we found stakes or not
        acceptedBlockChan, listener := InitAcceptedBlockUpdate(eventBroker)
 
+       if currentHeight == 0 {
+               roundBytes := make([]byte, 8)
+               binary.LittleEndian.PutUint64(roundBytes, 1)
+               eventBroker.Publish(msg.InitializationTopic, bytes.NewBuffer(roundBytes))
+               return nil
+       }
+

```

**Comment by julesdesmit** [comment]
>However, in case of starting the network from genesis block, wouldn't the network get stuck as no node is able to generate block at height 1?

This can be worked around by using the internal `walletgenesis.dat`, which is currently kept in `dusk-buddy`. The wallet has a stake and bid attributed to it in block 0, so that it can bootstrap the consensus by itself and allow others to join.

Note by the way, that the patch you suggest would be moot if #25 were merged. It should allow for the generation component to start on it's own as a bid would be found, and the provisioner components to be started automatically as searching for stakes was removed, since it was deemed unnecessary.

**Comment by ggoranov** [comment]
> This can be worked around by using the internal walletgenesis.dat, which is currently kept in dusk-buddy. The wallet has a stake and bid attributed to it in block 0, so that it can bootstrap the consensus by itself and allow others to join. A wallet file can be specified with -w I believe, if using the spawner script.

The local network has a node that loads the genesis wallet. But it does not initialize the consensus as  `msg.InitializationTopic`  is never published.

**Comment by julesdesmit** [comment]
>The local network has a node that loads the genesis wallet. But it does not initialize the consensus as msg.InitializationTopic is never published.

That's correct, my mistake. Even with #25 merged, it would still need to see at least one block before starting up, so the patch should take care of it.
