### ISSUE TITLE
Fix race condition between round updates and agreement event creation

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#62]
As observed on the testnet, a possibility exists for the node to unintentionally offset it's agreement component step counter due to the `agreement.broker.Listen` goroutine being entirely seperate from the invocation to `agreement.broker.sendAgreement` (which happens as a callback from the reduction component). As aggregating the reduction events into an agreement event takes some amount of time (I believe it's a few hundred ms), there's an opening for the round update to happen in the midst of this. After the aggregation is complete, and the state is updated, the deferred call to `broker.state.IncrementStep` is executed, and the node then starts off that round with an agreement step counter that is ahead by one.

As a result, any events that are created next, will be invalid. This happens because the committee bitset that gets generated is dependent on the `broker.state.Step`, meaning that for reduction events created on step 1 and 2, the agreement event contains a bitset corresponding to these events in the committees from step 3 and 4. This causes an inconsistency in the network and, if enough nodes are affected on the same round, it can halt consensus entirely since too many nodes will not be able to generate proper agreement events, regardless of how many times they try.

This bug was reproduced in a test, which will be included in the PR to fix this. I believe a simple fix would just be to invoke the `sendAgreement` function through a channel, instead of a callback, which would synchronize it with the occurrence of round updates, thus keeping the step counter in it's correct place at any time.

**Comment by autholykos** [comment]
As a side note, most probably `agreement.broker` could maybe use a concurrent strategy to speed-up signature aggregation as highlighted in dusk-crypto/issues#14

**Comment by julesdesmit** [comment]
@autholykos Good point, should we make a seperate issue for this?
