### ISSUE TITLE
Remove Config singleton invokations

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#623]
Configuration should not be used directly within the components, but parsed by the main process and passed along. An example of that can be found [here](https://github.com/dusk-network/dusk-blockchain/blob/9ffce551412acd4e142094b5a7310b16ad2ff34e/pkg/rpc/server/setup.go#L45). The reason for something like this, would be ease of testing.

**Comment by autholykos** [comment]
See https://github.com/dusk-network/dusk-blockchain/pull/622#pullrequestreview-465671236

**Comment by devtomnl** [comment]
Few of the changed files may require more thought since they do not have constructors.
`initiator.go`
`aggregator.go`
`mempool.go`
`datarequestor.go`

**Comment by autholykos** [comment]
Closing as obsolete
