### ISSUE TITLE
Counter is passed to various components and is a component itself

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#670]
Take a stance! Either it is a component and it should only react through the RPCBus and/or the EventBus; or it is a struct and it should be passed directly to the components of the architecture. At the moment we treat it as both

**Comment by autholykos** [comment]
After browsing the code where the `counter` is used, the impression is that the counter should be a simple struct using an `atomic` `uint32` directly accessed without querying the `rpcbus`

**Comment by julesdesmit** [comment]
Merged via #673
