### ISSUE TITLE
Consider splitting the Provisioner and the BlockGenerator rewards in two different coinbases

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#710]
At the moment, the BlockGenerator is creating the coinbases for both itself and the Provisioners of the last block. This means that the Provisioners are rewarded with one round delay compared to the generator. While this is mainly acceptable, it might be simpler to reason in terms of two different coinbases, one for the `BlockGenerator` and another for the `Provisioners`. This way, the latter would be generating their own coinbase in the `Agreement` step and get rewarded in the same round they operate, which might lead to code simplification. 

Since the Provisioners are public anyway, the second coinbase would not need a proof, which might also make the call to `Distribute` contract slightly faster

**Comment by julesdesmit** [comment]
Obsolete due to changes to the selection phase.
