### ISSUE TITLE
The whole core/transactor package should be implemented correctly

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#714]
The transactor package contains the logic to store the users' based parameters necessary to use the blindbid algorithm. At the moment, all parameters are mocked and hardcoded. Moreoever, the parameters are largely obsolete (like the `EdPk`) and need to be updated according to the transaction specs

**Comment by autholykos** [comment]
This includes the `Transaction.FetchBidValues()` and `Transaction.StoreBidValues()` interface method of `core/database`

**Comment by julesdesmit** [comment]
This issue should be moved to another epic concerning final RUSK integration, as we can not properly implement the creation of D and K without finalized specs and a functional RUSK server.

**Comment by julesdesmit** [comment]
Obsolete due to changes to the selection phase.
