### ISSUE TITLE
Aggregators for logs and Dashboards - ELK + Filebeat

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#716]

**Comment by pmoranga** [comment]
commit 5db1027a79e3ed9dbb1e8fae9adf9b27354dba45 (HEAD -> monitoring)
Author: pmoranga <pmoranga@comscore.com>
Date:   Wed Dec 23 01:42:56 2020 +0100

    This is intial work of tickets #716, #722, #721
    
    Here we deploy:
    
    - Traefik: route all traffic and SSL (Let's Encrypt) management
    - Prometheus: with simple scraping rule for now
    - Grafana: Set up for prometheus
    - Kibana: Set up for ElasticSearch
    - Elastic Search and tools
