### ISSUE TITLE
Monitoring panics and send sms / email alerts

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#717]

**Comment by pmoranga** [comment]
Having a local script / program (monit? ) that monitors PID, and sends email when it’s down.

**Comment by pmoranga** [comment]
@Fulviuus I need an email for the alerts. Also an SMS Gateway API provider keys (You mentioned Twilio mentioned on our conversations). Can you create an account and provide an API key with permission for SMS only ?

**Comment by pmoranga** [comment]
As discussed with Fulvio, we will trigger notification via Telegram other then SMS.

**Comment by pmoranga** [comment]
Implemented Telegram and e-mail.
