### ISSUE TITLE
Deploy-er need to be refactored in order to have the ELK + File-beat integrated

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#718]

**Comment by pmoranga** [comment]
https://github.com/dusk-network/dusk-deployer/commit/dcc499951f7c6591be04d37c21e0cbe1f1c8750b

Install collectors for ElasticSearch:

- MetricBeat - Collect OS and Dusk (prometheus format) metrics
- FileBeat - Collect OS and Dusk logs 

Still pending to secure data transfer to Elastic Search

**Comment by pmoranga** [comment]
This is done, SSL during transfer will be handled on another ticket
