### ISSUE TITLE
Deploy Prometheus DB with a Ansible script

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#721]

**Comment by pmoranga** [comment]
commit 5db1027a79e3ed9dbb1e8fae9adf9b27354dba45 (HEAD -> monitoring)

    This is intial work of tickets #716, #722, #721
    
    Here we deploy:
    
    - Traefik: route all traffic and SSL (Let's Encrypt) management
    - Prometheus: with simple scraping rule for now
    - Grafana: Set up for prometheus
    - Kibana: Set up for ElasticSearch
    - Elastic Search and tools

**Comment by pmoranga** [comment]
Prometheus is deployable with current ansible configuration

**Comment by pmoranga** [comment]
As Metric Beat and ElasticSearch fulfil this requirement, we wont do prometheus, neither grafana
