### ISSUE TITLE
Remove global channels in RPCBus source file, and find another way to implement them

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#73]
The RPCBus had it's channels implemented as global variables due to simplicity (according to @ggoranov). However, this approach can be quite unsafe, as there is no guarantee that the correct component is reading a request - even if the intent is to only have the channel strictly between two components, this is not mentioned anywhere (as far as I can tell, if I missed it please let me know), and in such a case it would still be better to return it from a function call or something similar, so to not make that particular channel available to the rest of the code since it shouldn't be shared outside of those components in the first place. Anybody not properly familiar with this code could easily make a mistake that way.

**Comment by autholykos** [comment]
+1

It should also be said that these global variables are actually a significant obstacle when trying to test or benchmark the components

**Comment by ggoranov** [comment]
Agreed! Go for it!

> if the intent is to only have the channel strictly between two components, this is not mentioned anywhere

Nope, the intent was to provide Multi-Consumer support. 
For instance, `getLastBlock` command could be handled by both `chain` component and `database `component`.

That said, while the chain component is busy verifying the latest block to be accepted, another component (like database) could also provide `getlastblock` to any consumer like block explorer without blocking.

But that's more like a hidden feature and it's not important for now.

**Comment by ggoranov** [comment]
Speaking about refactoring RPCbus, feel free to suggest more appropriate name for the component as RPCBus (remote procedure call) still sounds a bit misleading whereas RPCBus is for internal request-response communication only

**Comment by julesdesmit** [comment]
I'm currently debating the idea of removing channels from the RPCBus altogether and basing it purely on callbacks.

Some pros would be:
- Marginally more efficient (channels have been proven to be slower than mutexes)
- Simplifies the RPCBus slightly, as it removes the need for a Request object altogether. Responders could simply register a function with a uniform signature. Requesters will then receive the return value on calling `Call()`.
- Simplifies tests. If the RPCBus works with callbacks there would be no need for setting up listening goroutines which can hang and cause race conditions.

Some cons would be:
- Requires locking a few components. The mempool and the transactor come to mind, which currently work (to my knowledge) purely with channels, which allows them to be mutex-free.
- Other components which make use of the RPCBus would need to be refactored to instead register a callback to the RPCBus.
- No freedom for the caller to time-out the sending of a request, or the receiving of a response. May cause other components to be deadlocked.

**Comment by ggoranov** [comment]
I'd stick to the idea of a reactor-pattern for each component.  Both rpcBus and eventBus communicating via channels do support this rule perfectly. 

> Marginally more efficient (channels have been proven to be slower than mutexes)

If we really need to improve perf, I'd suggest to start with reviewing top10 bottlenecks (from go tool pprof). 

> Simplifies tests. If the RPCBus works with callbacks there would be no need for setting up listening goroutines which can hang and cause race conditions.

Don't we need already to set up listening routines due to the event-driven communication?


In general, to address this issue 73, I've chosen a different way of registering the methods as per https://github.com/dusk-network/dusk-blockchain/blob/master/pkg/core/transactor/transactor.go#L80.

**Comment by julesdesmit** [comment]
> Don't we need already to set up listening routines due to the event-driven communication?

Not with callbacks, as there is no listening routine involved. I'm talking specifically about instances like the reduction test file, where we need to set up this goroutine for the candidate block verification procedure.

> In general, to address this issue 73, I've chosen a different way of registering the methods as per https://github.com/dusk-network/dusk-blockchain/blob/master/pkg/core/transactor/transactor.go#L80.

I don't really see how this gets rid of using global channels.

I will stick to channels for now, I've been in refactoring mode for the past week or so and the idea came to me as we're working to eliminate unnecessary asynchronism in the node to improve performance and simplify some code, but the change for the RPCBus to work purely on callbacks would be quite drastic and outside of the scope of this issue.

**Comment by ggoranov** [comment]
> I don't really see how this gets rid of using global channels.

The suggestion from above uses package scoped variables (instead of global vars). If needed, these channels could be bundled as an instance variable. This addresses the `this approach can be quite unsafe, as there is no guarantee that the correct component is reading a request` as the Consumer component is responsible to self-registering.

**Comment by julesdesmit** [comment]
This still could produce test complications which we are trying to avoid - for instance, if we added tests for the `transactor` package (which we probably should), and the test was running on any other setting than `-p 1`, these channels are still shared by the different tests and can cause hard to debug test failures.

Why not just opt for including the channels in the `Transactor`? Is there a specific advantage of using package scoped variables over just putting them as struct fields?

**Comment by ggoranov** [comment]
> Why not just opt for including the channels in the Transactor?

Correct. This is what I meant by `If needed, these channels could be bundled as an instance variable.`

**Comment by julesdesmit** [comment]
The current issue is actually related to testing, as posted earlier:

> It should also be said that these global variables are actually a significant obstacle when trying to test or benchmark the components

This is also what I was talking about in my last comment. If you deem the setup to be a problem then open a seperate issue for it.
