### ISSUE TITLE
Update deployer by adding a core role that will be used to setup nodes with basic configs

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#730]
Required tasks to be added to the core commons playbook:

1. Make sure that all packages are updated to the latest versions
 
2. Alter the login message when a user logs in into the machine 

3. Create Dusk group

4. Create dusk user

5. Create dusk directories

**Comment by julesdesmit** [comment]
Fixed in dusk-deployer. Issue should also not have been filed here.
