### ISSUE TITLE
Consider exposing wallet commands as an API

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-blockchain#74]
Currently, the entire wallet interaction goes through CLI commands. A client application is not capable of creating a transaction, getting balance and so on. 
An example: To enable test-harness, rpc package is calling `cli.SendBidTx` directly as a temporary patch.

Proposal:

Wallet commands can be moved to a separate package so that both CLI and RPC  packages can use them via RPCBus.

Other option could be to deprecated CLI entirely and build RPC API only for interaction with the wallet.

Let me know your thoughts on that.
@julesdesmit @autholykos

**Comment by julesdesmit** [comment]
I've been working on something similar for #27, it currently features a `Transactor` process which other components can invoke through event bus calls, to construct and propagate transactions. 

I'm still working out the details, I was debating maybe to remove the event bus from the equation and instead just passing it around, or instantiating it in the components which need this, as there's no advantage (as far as I could tell) for this component to really be asynchronous, or decoupled as such. If it were decoupled, it would need the `RPCBus` for balance calls, which I would rather avoid as it would (needlessly) complicate the design and the tests (for one, the timeout would be variable since we can't infer how long the sync would take).

Other than that, the name needs a change because `Transactor` is not really a proper name as it also syncs the wallet and checks the balance, but again, still working out the details. :)

**Comment by ggoranov** [comment]
>  it currently features a Transactor process which other components can invoke through event bus calls, to construct and propagate transactions.

It' would be good to allow retrieving result from the wallet command executing. E.g When sending a tx, a client would need the txid or error as an output. Eventbus between producer and consumer wouldn't handle this easily.

> passing it around, or instantiating it in the components which need this
Could be. Maybe in that case we'll need to protect both walletDB and wallet.dat from simultaneous reads/writes

> (for one, the timeout would be variable since we can't infer how long the sync would take)

Do we really need syncing to be performed on each wallet command? I assume long syncing make sense on loading a wallet for the first time but once loaded, the walletDB can be re-synced automatically on acceptedBlock event

**Comment by julesdesmit** [comment]
> It' would be good to allow retrieving result from the wallet command executing. E.g When sending a tx, a client would need the txid or error as an output. Eventbus between producer and consumer wouldn't handle this easily.

Agreed, also part of the reason why I was debating removing the event bus from this process and instead just creating a struct with the proper methods and return values.

> Maybe in that case we'll need to protect both walletDB and wallet.dat from simultaneous reads/writes

wallet.dat would be fine, we should check for walletDB though. wallet.dat only contains the bytes for a seed. walletDB could be in trouble if two components sync simultaneously, so a simple mutex would get rid of that issue.

> Do we really need syncing to be performed on each wallet command?

Yes. Unless we are synced before doing any action, we can not guarantee we are retrieving unspent outputs, and we can not guarantee a proper balance either.

> the walletDB can be re-synced automatically on acceptedBlock event

Possible, but again it makes things a bit more complex than they need to be. If the `Transactor` is owned by whatever component needs it, it would be a lot simpler to just sync whenever any method is called on it.

**Comment by ggoranov** [comment]
> wallet.dat would be fine, we should check for walletDB though

Regarding the wallet.dat, I meant the case where `createWalletCMD` is used by different go-routines. Then, some synchronization might be needed.

> Possible, but again it makes things a bit more complex than they need to be. If the Transactor is owned by whatever component needs it, it would be a lot simpler to just sync whenever any method is called on it.

Not sure what you mean by complex as we've got many components collecting acceptBlock already. Note that if sending a transaction is delayed by minutes because of scanning blocks/txs for the past week, this might be obstacle in some situations.

**Comment by julesdesmit** [comment]
> Regarding the wallet.dat, I meant the case where createWalletCMD is used by different go-routines. Then, some synchronization might be needed.

`createWalletCMD` would still be something only the CLI can do. The `Transactor` would just create transactions after a wallet is loaded. It can then be passed around for all components to be using the same wallet.

> Not sure what you mean by complex

The `Transactor` would need to be hooked up with an `acceptedBlockChan` and needs a goroutine to listen for it. This can be done, but it would be simpler to just have it done on the method call as it involves no extra wiring of channels and no extra goroutine, hence extra complexity.

> Note that if sending a transaction is delayed by minutes because of scanning blocks/txs for the past week, this might be obstacle in some situations.

Like we do currently, printing the sync progress could do just fine, as it provides feedback about why it is taking a while. As far as E2E testing goes, I do not assume we are going to have to sync a ridiculous amount of blocks, so it should not slow down testing.

I do also see the positives of syncing it on each accepted block, but I would rather keep things simple for now. Regardless, this isn't a big point of contention for me, if you think it would be greatly advantageous to go with that route, then we can go for it.

**Comment by ggoranov** [comment]
Up to you! My wish is that we can provide instant transactions with guaranteed confirmation time, if that makes sense.
