### ISSUE TITLE
`Provisioners` and `BidList` should be immutable, and come from a single source of truth

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#79]
As of right now, the `Provisioners` and `BidList` are instantiated once per component that uses them, and they are either self-managed, or managed by the component using them. This is unnecessary and perhaps even dangerous, since risk of being out of sync greatly increases. As these structures are mostly mutated by new information put on the blockchain, the `Chain` should hold these data structures and be able to provide copies of them on request (RPCBus). This ensures that the provided data is continuous between different components, and reduces the risk of a desync due to a message delivery failure.

**Comment by autholykos** [comment]
+1
This would also present the advantage to eliminate a whole lot of unnecessary locking, since it could provide the opportunity of returning the `BidList` and the `Provisioners` _by value_, without the need for a shared reference.

**Comment by julesdesmit** [comment]
Let me add as well that we should absolutely persist these structures to disk storage - see #55
