### ISSUE TITLE
Implement nightly test-harness action for stress testing 

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#862]
Currently, `test-harness-ci` is based on 3 nodes only. This is quite insufficient when problematic edge-case scenarios like #847 and #855 are deeply hidden.  On a nightly basis github action that bootstraps test-harness and leaves it running for a couple of hours should allow us to catch hardly reproducible issues on time.

This is a proposal for `test-harness-nightly` github action that will:

1. Start test-harness 02:00 GMT every night
2. Bootstrap initially a network of 10 nodes (provisioners)
3. Each 10 mins another bucket of 3 nodes (provisioners) will join the network
4. After 3 hours running, ensure that consensus average time is less than 30 sec and all network nodes are synced up.

NB. Parameters could be readjusted depending on the environment capabilities.

In addition, later on `test-harness-nightly` could be extended with various other edge-case scenarios concerning transactions.

**Comment by julesdesmit** [comment]
Isn't DevNet specifically for this purpose, but just on longer timeframes? That said, I do think the periodic adding of nodes + health checks would be a good idea to incorporate in the DevNet, as well as some kind of CD pipeline that restarts the process when master is updated.

**Comment by goshawk-3** [comment]
Agreed.
