### ISSUE TITLE
Use devnet-wallets in test-harness

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/dusk-blockchain#863]
In order to maintain only a single source of wallets for testing `test harness` should use wallet data files stored in `dusk-blockchain/devnet-wallets` instead of `dusk-blockchain/harness/data/`. In addition, this will allow us to run test-harness with more than 10 nodes (up to 119)

**Comment by julesdesmit** [comment]
They are already being used, and were swapped in the commit https://github.com/dusk-network/dusk-blockchain/commit/28b9b3de31210254b8ab1294776dc551ca3ab399.
