### ISSUE TITLE
Change linter to be more strict about code styling rules

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#865]
One such rule is not to leave whitespace between the function declaration and function body.

> Maybe to ensure this and any other Style rules, `go fmt` and  `go linter` should be extended.

_Originally posted by @goshawk-3 in https://github.com/dusk-network/dusk-blockchain/pull/864#discussion_r560872779_

**Comment by goshawk-3** [comment]
We can also check if any gofmt-like tool already can format functions body with this rule.

**Comment by julesdesmit** [comment]
@goshawk-3 On that note, it seems [gofumpt](https://github.com/mvdan/gofumpt) would do the trick.
