### ISSUE TITLE
Refactor the synchronizer-chain-consensus pipeline for clarity and maintainability

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#882]
From the current code, it is quite unclear how messages are passed down from the synchronizer onwards. When the consensus is running, messages coming through `CatchBlockChan` actually go to the `Agreement` goroutine first, and from there on are bubbled back up to `produceBlock` in the `Chain` - which is not evident when you read the code.

This pipeline needs to be redesigned. In my opinion, I think we should aim for a more synchronous approach, like the last iteration (where the `Chain` handled both syncing and consensus). We encountered no race conditions with such a setup, however, the `Chain` had quite a lot of responsibility, so we should take that into account for the redesign. An ideal solution would be easily readable and provably stable.

Other suggestions are of course welcome. @autholykos @goshawk-3

**Comment by autholykos** [comment]
Changed into an Epic as the solution to this will probably comprise of multiple actionable issues
