### ISSUE TITLE
Re-evaluate usefulness and correctness of the Verifier/Loader interfaces

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#925]
The `Loader` seems to have more responsibilities than its name suggests - it also is used to append blocks and fetch state from the DB.

Additionally, the `Verifier` interface seems a bit unnecessary. The `verifiers` package exposes all the checks that the `Chain` can make, but the `Verifier` doesn't actually use all of them, which seems like a strange choice - which subsequently affects testing, since we can not mock certificate checks for instance.

**Comment by autholykos** [comment]
A thorough assessment of the `Chain` should be done during the imminent migration to rust
