### ISSUE TITLE
Investigate cause of RUSK mock server crash on devnet

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#936]
On the DevNet, a node was observed getting stuck after around 43,000 blocks. The cause of this seemed to have been a context deadline being exceeded by the `ExecuteStateTransition` function. After checking the list of active processes, it looked like the mock rusk server had been restarted, as the uptime was vastly different from the node's uptime.

The cause of the crash will need to be investigated and fixed in order to promote a stable DevNet.

**Comment by autholykos** [comment]
Duplicate of #951
