### ISSUE TITLE
Investigate the role RUSK plays in transaction validation in the mempool

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#941]
Currently, the `UnconfirmedTxProber` is used to outsource some verification logic to RUSK. However, there is no mention of the method (`VerifyTransaction`) anywhere in any of the schemas, and I could not find any information about this on the knowledge base. Therefore, I would like to ask @toghrulmaharramov to elaborate on this process.

**Comment by toghrulmaharramov** [comment]
Before being added to the mempool, the transaction has to be verified with the Execute method of DUSK Contract. Specifically, steps 1,2,4,7,8,9 and 10 from Execute method should be executed and verified whether $ g_{l} $ from step 7 is greater or equal than the gas to be consumed by steps 1-10; 12-18. If those checks pass, then the transaction can be added to the mempool.

**Comment by julesdesmit** [comment]
Makes perfect sense!

**Comment by autholykos** [comment]
@toghrulmaharramov please add the documentation on gitbook. After that, the issue can be considered closed

**Comment by toghrulmaharramov** [comment]
Added to the GitBook under Node/Transaction Verification section.
